--- # Open the ProfanityFilter CI at https://poggit.pmmp.io/ci/ReinfyTeam/ProfanityFilter
build-by-default: true
branches:
- main
projects:
  ExamplePlugin:
    path: ""
    libs:
      - src: ReinfyTeam/libpf/libpf
        version: ^0.0.4
...
